- name:          template1.yml
  import_tasks:  db/template1.yml

- name:          postgres.yml
  import_tasks:  db/postgres.yml

- name:          ioannis.yml
  import_tasks:  db/ioannis.yml

- name:          bench.yml
  import_tasks:  db/bench.yml

- name:          ts.yml
  import_tasks:  db/ts.yml

- name:          timescaledb.yml
  import_tasks:  db/timescaledb.yml
