############################### Roles  ##############################################################################
# NOTE: We are assuming flyway is not imployed

- name:            create postgres and replication
  when:             
                   - postgres_passwd    is defined
                   - repl_and_pg_roles 
  postgresql_user:  name="{{item.name}}"   role_attr_flags="{{item.attr}}"  password="{{ item.passwd |default(omit) }}"  encrypted=yes  ssl_mode="prefer"   port="{{ pport }}" login_password="{{postgres_passwd|default(omit)}}"  login_host=localhost 
  with_items:
        - { name: postgres,      passwd: "{{postgres_passwd}}", attr: superuser   }
        - { name: replication,   passwd: "{{postgres_passwd}}", attr: replication }

- name:             create roles 
  postgresql_user:  name="{{item.name}}"   role_attr_flags="{{item.attr | default(omit)}}" password="{{item.passwd|default(omit)}}"  encrypted="yes"  ssl_mode="prefer"   port="{{ pport }}" login_password="{{postgres_passwd|default(omit)}}"  login_host=localhost 
  with_items: "{{  users  }}"


#
################################## template1   ######################################################################
- name: plpgsql
  postgresql_lang:  db=template1  lang=plpgsql   trust=yes  state=present port="{{ pport }}" login_password="{{postgres_passwd|default(omit)}}"  login_host="localhost"
    
################################### Databases  #####################################################################
- name:   db bench
  postgresql_db: name="bench" owner="ioannis" encoding="UTF-8" lc_collate="en_US.UTF-8"  template=template0  port="{{ pport }}" login_password="{{postgres_passwd|default(omit)}}"  login_host="localhost"

- name:   db ioannis
  postgresql_db: name="ioannis" owner="ioannis" encoding="UTF-8" lc_collate="en_US.UTF-8"  template=template0  port="{{ pport }}" login_password="{{postgres_passwd|default(omit)}}"  login_host="localhost"

################################# Extensions  #######################################################################
- name:     ext for database ioannis
  postgresql_ext:  name={{item}}  db=ioannis port="{{ pport }}" login_password="{{postgres_passwd|default(omit)}}"  login_host="localhost"
  with_items:
         - pgtap
           #- file_fdw
           #- pg_stat_statements #- pg_qualstats #- pg_stat_kcache


################################ Privs     ###########################################################################
- name:  privs for database postgres 
  postgresql_privs:   db="postgres"  privs=CONNECT  type=database  roles="{{item}}" port="{{ pport }}" login_password="{{postgres_passwd|default(omit)}}"  login_host="localhost"
  with_items:
        - nagios
        - ioannis

  postgresql_privs:   db="postgres" grant_option="no"  privs="INSERT,UPDATE"  type="table" obj="ALL_IN_SCHEMA"  schema="public" roles="{{item}}"  port="{{ pport }}" login_password="{{postgres_passwd|default(omit)}}"  login_host="localhost"
  with_items:
        - nagios
