- name:            python
  apt:
     pkg:
                  - python-apt
                  - python-pip
                  - python-psycopg2
                  - python3-apt
                  - python3-pip
                  - python3-psycopg2


