---
# Assumptions: 
#    - postmaster  is not running
#    - ansible executes as unix user 'postgres'
#    - cluster has been initialized and pg_hda allows role 'postres'to connect 
#    - we will not configure osx hosts because psycopg2 might be hard to install through macports
# Post conditions:
#   - pg_hba.conf is updated  or left untouchd, depending on user options 
#   - created postgres roles with passwords
#   - added to template1
#   - created  databases, extensions, languages, and set privs
#   - enabled replication via uses 'postgres' and 'replication' (see pg_hba.conf)


- name:           fail unless ansible executing as unix user postgres
  when:           not (ansible_user_id == "postgres")
  fail:           msg="Detected ansible_user_id='{{ ansible_user_id}}'. This role must run as 'postgres'"

- name:           ensure postmaster is running 
  shell:          ~postgres/dist-pg/bin/pg_ctl -D {{ cluster_path }} -o '-c ssl=off'  start
  ignore_errors:  yes
  environment:  
          PATH:     "{{ ansible_env.PATH }}:/Users/postgres/dist-pg/bin:/home/postgres/dist-pg/bin:/usr/bin"

########################################################## Decide on Liquibqse, Flyway, or Manual
- name:          under Flyway?  
  shell:         psql -h localhost -U postgres -p 5434 -d postgres -c 'table "{{ changelog }}"'  > /dev/null
  when:          
      - changelog is defined
      - false
  environment:
          PATH:     "{{ ansible_env.PATH }}:/Users/postgres/dist-pg/bin:/home/postgres/dist-pg/bin:/usr/bin"
  register:      result
  ignore_errors:  yes

### Configure database if no changelog was either not defined or not found in database 'postgres'
- name:          manual config
  when:          not ( use_flyway or use_liquibase)
  import_tasks:  manual.yml

- name:          flyway
  when:          use_flyway 
  import_tasks:  flyway.yml

  #- name:          liquibase
  #when:          use_liquibase
  #  import_tasks:  liquibase.yml
################################## Reload, then Stop postmaster unless user wanted otherwise
- name:            reload {{ cluster_name }} 
  shell:          "pg_ctl -D {{ cluster_path  }} reload"
  environment:  
          PATH:     "{{ ansible_env.PATH }}:/Users/postgres/dist-pg/bin:/home/postgres/dist-pg/bin:/usr/bin"

- name:            keep postmaster running ?
  when:            not (keep_running)
  ignore_errors:   yes
  shell:          "pg_ctl -D {{ cluster_path }} stop"
  environment:  
          PATH:     "{{ ansible_env.PATH }}:/Users/postgres/dist-pg/bin:/home/postgres/dist-pg/bin:/usr/bin"
