
- name:         database "template1"
  script:       script/db/template1.sh   localhost   "{{ pport }}"
  environment:  
      - PATH:    "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"

- name:         database "postgres"
  script:       script/db/postgres.sh   localhost   "{{ pport }}"
  environment:  
      - PATH:    "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"

- name:         database "ioannis"
  script:       script/db/ioannis.sh   localhost   "{{ pport }}"
  environment:  
      - PATH:    "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"

- include:      db/ts.yml         
  #when:         not minimal

- name:         database "bench"
  script:       script/db/bench.sh   localhost   "{{ pport }}"
  when:         not minimal
  environment:  
      - PATH:    "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"

- name:         database "timescaledb"
  when:         not minimal
  script:       script/db/timescaledb.sh   localhost   "{{ pport }}"
  environment:  
      - PATH:    "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"
