- name:         database "ts"
  script:       script/db/ts.sh   localhost   "{{ pport }}"
  environment:  
      - PATH:    "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"

- name:         ls.sh
  become_user:  postgres
  become:       yes
  script:       script/db/ts/ls.sh   localhost   "{{ pport }}"
  environment:  
      - PATH:    "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"

- name:         pg_stat_statments.sh
  become_user:  postgres
  become:       yes
  script:       script/db/ts/pg_stat_statements.sh   localhost   "{{ pport }}"
  environment:  
      - PATH:    "/home/postgres/dist-pg/bin:/bin:/usr/bin:/usr/local/bin"

